### ISSUE TITLE
[feature request] http server example

### ISSUE THREAD

**Issue by silvioprog** [JacobLinCool/smart-whisper#20]
Hey, thanks a lot for this amazing and promising project! ❤️

So, it would be nice to add some example, like integrating this with Express, processing uploaded files directly via streaming, instead of uploading and saving the file in local file system.

cheers

**Comment by JacobLinCool** [comment]
AFAIK, streaming is not supported in whisper.cpp. Their streaming example involves passing audio segments one by one with some previous transcription as the context prompt.

I do have working server code [here](https://github.com/JacobLinCool/whisper-cli/blob/main/packages/whisper-cli/src/smart/server.ts), which uses Fastify as the server framework. However, to support more formats, it does save the file to the disk and uses FFmpeg to convert it to 16k mono WAV.

Here is an Express example provided by ChatGPT that doesn't write files to the disk; it might be a good starting point:
```ts
import express from 'express';
import multer from 'multer';
import { decode } from 'node-wav';
import { Whisper } from 'smart-whisper';

const app = express();
const upload = multer(); // multer in-memory storage
const port = 3000;

// Initialize Whisper with the desired model
const modelPath = 'path/to/your/model';
const whisper = new Whisper(modelPath, { gpu: true });

app.post('/transcribe', upload.single('audio'), async (req, res) => {
    if (!req.file) {
        return res.status(400).send('No file uploaded.');
    }

    try {
        // Decode the WAV file from the buffer
        const pcm = readWav(req.file.buffer);

        // Transcribe the audio file
        const task = await whisper.transcribe(pcm, { language: 'auto' });
        const results = await task.result;

        // Send the transcription results
        res.json(results);
    } catch (error) {
        console.error(error);
        res.status(500).send('Error processing the audio file.');
    }
});

app.listen(port, () => {
    console.log(`Server is listening on port ${port}`);
});

function readWav(buffer: Buffer): Float32Array {
    const { sampleRate, channelData } = decode(buffer);

    if (sampleRate !== 16000) {
        throw new Error(`Invalid sample rate: ${sampleRate}`);
    }
    if (channelData.length !== 1) {
        throw new Error(`Invalid channel count: ${channelData.length}`);
    }

    return channelData[0];
}
```

> I would like to add it to examples in the next release.

**Comment by silvioprog** [comment]
Oh, I didn't know you are already working on a server. This is excellent news! 🤩

Let's keep the Express example here for further references. And thanks a lot for sharing this.

I'll take a look at the server you are working on. See you there!
