### ISSUE TITLE
[feature request] detected spoken language

### ISSUE THREAD

**Issue by silvioprog** [JacobLinCool/smart-whisper#40]
Hi.

It would by really useful if we could return the spoken language in the audio, something [like this](https://github.com/ggerganov/whisper.cpp/blob/2948c740a2bf43190b8e3badb6f1e147f11f96d1/examples/main/main.cpp#L629).

So, we would have a property returning `en`, `pt`, `es` etc.

TIA

**Comment by silvioprog** [comment]
I'm going try to provide a PR.

**Comment by JacobLinCool** [comment]
I think I can work on a PR for that.

**Comment by silvioprog** [comment]
I was working in a PR, but not sure if the correct implementation. Should I try to send it anyway for a code review?

**Comment by JacobLinCool** [comment]
Wow! That's amazing! I'll happy to review that when you are ready.

**Comment by silvioprog** [comment]
A little delayed, but finally PR sent https://github.com/JacobLinCool/smart-whisper/pull/43 🙌
